require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance
  - rubocop-thread_safety

Style/Documentation:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Performance/StringReplacement:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "test/**/*"
